import json
from pathlib import Path

nb_path = Path(r"c:\Users\godso\Desktop\FMN-Supply-Chain\Backend\app\pipeline\supply_chain_pipeline.ipynb")

nb = {
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# Supply Chain Demand and Risk Pipeline\n",
        "\n",
        "This notebook combines the full pipeline used for the FMN supply chain solution:\n",
        "1. Explore the available demand and inventory data\n",
        "2. Clean and validate the raw sales data\n",
        "3. Engineer demand and stock-risk features\n",
        "4. Build the leakage-safe modeling dataset\n",
        "5. Train a time-based demand forecasting model\n",
        "6. Forecast demand and classify SKU risk\n",
        "7. Save the outputs for the API and frontend\n",
        "\n",
        "Run the cells in order."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "from pathlib import Path\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import joblib\n",
        "from sklearn.ensemble import RandomForestRegressor\n",
        "from sklearn.metrics import mean_absolute_error\n",
        "\n",
        "PIPELINE_DIR = Path.cwd()\n",
        "ROOT_DIR = PIPELINE_DIR.parent\n",
        "DATA_DIR = ROOT_DIR / 'data'\n",
        "RAW_PATH = DATA_DIR / 'raw_data.csv' if (DATA_DIR / 'raw_data.csv').exists() else PIPELINE_DIR / 'raw_data.csv'\n",
        "CLEANED_PATH = PIPELINE_DIR / 'cleaned_data.csv'\n",
        "FEATURES_PATH = PIPELINE_DIR / 'features.csv'\n",
        "MODEL_DATASET_PATH = PIPELINE_DIR / 'model_dataset.csv'\n",
        "MODEL_PATH = PIPELINE_DIR / 'demand_model.joblib'\n",
        "MODEL_COLUMNS_PATH = PIPELINE_DIR / 'demand_model_columns.joblib'\n",
        "RISK_PATH = PIPELINE_DIR / 'risk_flags.csv'\n",
        "NEW_SKUS = ['SKU-2000', 'SKU-2001', 'SKU-2002']\n",
        "\n",
        "print(f'Pipeline directory: {PIPELINE_DIR}')\n",
        "print(f'Data directory: {DATA_DIR}')\n",
        "print(f'Raw data exists: {RAW_PATH.exists()}')\n",
        "if RAW_PATH.exists():\n",
        "    print(f'Using raw data source: {RAW_PATH}')\n",
        "else:\n",
        "    print('No raw_data.csv found. Using the existing cleaned and feature outputs in the pipeline folder.')\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 0) Exploratory Data Analysis\n",
        "\n",
        "This section checks the quality of the demand and inventory data before feature engineering and modeling."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "source_path = CLEANED_PATH if CLEANED_PATH.exists() else RAW_PATH\n",
        "if not source_path.exists():\n",
        "    raise FileNotFoundError(f'No data source found at {source_path}.')\n",
        "\n",
        "source_df = pd.read_csv(source_path)\n",
        "if 'date' in source_df.columns:\n",
        "    source_df['date'] = pd.to_datetime(source_df['date'])\n",
        "\n",
        "print('Source file:', source_path)\n",
        "print('Rows x columns:', source_df.shape)\n",
        "print('\\nMissing values by column:')\n",
        "print(source_df.isna().sum().to_string())\n",
        "print('\\nDate range:')\n",
        "if 'date' in source_df.columns:\n",
        "    print(source_df['date'].min(), 'to', source_df['date'].max())\n",
        "print('\\nCategory distribution:')\n",
        "if 'category' in source_df.columns:\n",
        "    print(source_df['category'].value_counts().head(10).to_string())\n",
        "print('\\nDemand summary:')\n",
        "if 'units_sold' in source_df.columns:\n",
        "    print(source_df['units_sold'].describe().to_string())\n",
        "print('\\nInventory summary:')\n",
        "if 'closing_stock' in source_df.columns:\n",
        "    print(source_df['closing_stock'].describe().to_string())\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 1) Load and clean the raw data"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "def load_raw(path=RAW_PATH):\n",
        "    if not path.exists():\n",
        "        raise FileNotFoundError(f'Raw data not found: {path}')\n",
        "    df = pd.read_csv(path)\n",
        "    df['date'] = pd.to_datetime(df['date'])\n",
        "    return df\n",
        "\n",
        "def normalize_category(df):\n",
        "    df = df.copy()\n",
        "    df['category'] = df['category'].str.strip().str.title()\n",
        "    return df\n",
        "\n",
        "def drop_exact_duplicates(df):\n",
        "    df = df.copy()\n",
        "    before = len(df)\n",
        "    df = df.drop_duplicates(subset=['sku_id', 'date'], keep='first')\n",
        "    after = len(df)\n",
        "    print(f'Dropped {before - after} exact duplicate rows')\n",
        "    return df\n",
        "\n",
        "def fill_missing_units_sold(df):\n",
        "    df = df.copy()\n",
        "    df = df.sort_values(['sku_id', 'date'])\n",
        "    df['units_sold_imputed'] = df['units_sold'].isna()\n",
        "    df['units_sold'] = df.groupby('sku_id')['units_sold'].transform(\n",
        "        lambda s: s.interpolate(method='linear').round()\n",
        "    )\n",
        "    df['units_sold'] = df.groupby('sku_id')['units_sold'].transform(\n",
        "        lambda s: s.bfill().ffill()\n",
        "    )\n",
        "    return df\n",
        "\n",
        "def reconstruct_missing_closing_stock(df):\n",
        "    df = df.copy()\n",
        "    df = df.sort_values(['sku_id', 'date']).reset_index(drop=True)\n",
        "    df['closing_stock_imputed'] = df['closing_stock'].isna()\n",
        "    for sku, idx in df.groupby('sku_id').groups.items():\n",
        "        idx = list(idx)\n",
        "        for i in idx:\n",
        "            if pd.isna(df.loc[i, 'closing_stock']):\n",
        "                pos = idx.index(i)\n",
        "                if pos == 0:\n",
        "                    continue\n",
        "                prev_i = idx[pos - 1]\n",
        "                prev_stock = df.loc[prev_i, 'closing_stock']\n",
        "                implied = prev_stock - df.loc[i, 'units_sold'] + df.loc[i, 'units_received']\n",
        "                df.loc[i, 'closing_stock'] = max(implied, 0)\n",
        "    return df\n",
        "\n",
        "def fix_new_sku_lead_time(df):\n",
        "    df = df.copy()\n",
        "    df['lead_time_assumed'] = False\n",
        "    established = df[~df['sku_id'].isin(NEW_SKUS)]\n",
        "    cat_median_lead = (\n",
        "        established.groupby(['category', 'sku_id'])['lead_time_days']\n",
        "        .first()\n",
        "        .groupby('category')\n",
        "        .median()\n",
        "    )\n",
        "    for sku in NEW_SKUS:\n",
        "        mask = df['sku_id'] == sku\n",
        "        if not mask.any():\n",
        "            continue\n",
        "        cat = df.loc[mask, 'category'].iloc[0]\n",
        "        df.loc[mask, 'lead_time_days'] = int(cat_median_lead[cat])\n",
        "        df.loc[mask, 'lead_time_assumed'] = True\n",
        "    return df\n",
        "\n",
        "if RAW_PATH.exists():\n",
        "    df = load_raw()\n",
        "    print('Initial shape:', df.shape)\n",
        "    print('Unique categories before normalization:', sorted(df['category'].unique())[:10])\n",
        "    df = normalize_category(df)\n",
        "    df = drop_exact_duplicates(df)\n",
        "    df = fill_missing_units_sold(df)\n",
        "    df = reconstruct_missing_closing_stock(df)\n",
        "    df = fix_new_sku_lead_time(df)\n",
        "    print('Final cleaned shape:', df.shape)\n",
        "    print(df.head().to_string())\n",
        "else:\n",
        "    df = pd.read_csv(CLEANED_PATH)\n",
        "    print('Raw data not available in the workspace. Using existing cleaned_data.csv from the pipeline folder.')\n",
        "    print('Current cleaned shape:', df.shape)\n",
        "    print(df.head().to_string())\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# Save cleaned CSV to the pipeline folder\n",
        "df.to_csv(CLEANED_PATH, index=False)\n",
        "print(f'Saved cleaned data to {CLEANED_PATH}')\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 2) Engineer demand and risk features"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "def load_cleaned(path=CLEANED_PATH):\n",
        "    df = pd.read_csv(path)\n",
        "    df['date'] = pd.to_datetime(df['date'])\n",
        "    return df.sort_values(['sku_id', 'date']).reset_index(drop=True)\n",
        "\n",
        "def add_rolling_demand_features(df):\n",
        "    df = df.copy()\n",
        "    g = df.groupby('sku_id')['units_sold']\n",
        "    df['avg_sold_7d'] = g.transform(lambda s: s.rolling(7, min_periods=3).mean())\n",
        "    df['avg_sold_14d'] = g.transform(lambda s: s.rolling(14, min_periods=5).mean())\n",
        "    df['avg_sold_28d'] = g.transform(lambda s: s.rolling(28, min_periods=7).mean())\n",
        "    df['std_sold_28d'] = g.transform(lambda s: s.rolling(28, min_periods=7).std())\n",
        "    return df\n",
        "\n",
        "def add_volatility_features(df):\n",
        "    df = df.copy()\n",
        "    df['cv_sold_28d'] = (df['std_sold_28d'] / df['avg_sold_28d']).replace([np.inf, -np.inf], np.nan)\n",
        "    return df\n",
        "\n",
        "def add_trend_feature(df):\n",
        "    df = df.copy()\n",
        "    g = df.groupby('sku_id')['units_sold']\n",
        "    prior_14d = g.transform(lambda s: s.shift(7).rolling(14, min_periods=5).mean())\n",
        "    df['trend_ratio'] = (df['avg_sold_7d'] / prior_14d).replace([np.inf, -np.inf], np.nan)\n",
        "    return df\n",
        "\n",
        "def add_stockout_features(df):\n",
        "    df = df.copy()\n",
        "    df['is_stockout_day'] = (df['closing_stock'] == 0).astype(int)\n",
        "    df['stockout_rate_28d'] = df.groupby('sku_id')['is_stockout_day'].transform(\n",
        "        lambda s: s.rolling(28, min_periods=5).mean()\n",
        "    )\n",
        "    return df\n",
        "\n",
        "def add_cover_features(df):\n",
        "    df = df.copy()\n",
        "    df['days_of_cover'] = df['closing_stock'] / df['avg_sold_14d']\n",
        "    df['days_of_cover'] = df['days_of_cover'].replace([np.inf, -np.inf], np.nan)\n",
        "    df['cover_vs_leadtime'] = df['days_of_cover'] / df['lead_time_days']\n",
        "    return df\n",
        "\n",
        "clean_df = load_cleaned()\n",
        "clean_df = add_rolling_demand_features(clean_df)\n",
        "clean_df = add_volatility_features(clean_df)\n",
        "clean_df = add_trend_feature(clean_df)\n",
        "clean_df = add_stockout_features(clean_df)\n",
        "clean_df = add_cover_features(clean_df)\n",
        "\n",
        "clean_df.to_csv(FEATURES_PATH, index=False)\n",
        "print(f'Saved feature table to {FEATURES_PATH}')\n",
        "print(clean_df.head().to_string())\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 3) Build the leakage-safe modeling dataset"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "LAG_FEATURES = [\n",
        "    'avg_sold_7d', 'avg_sold_14d', 'avg_sold_28d', 'std_sold_28d',\n",
        "    'cv_sold_28d', 'trend_ratio', 'stockout_rate_28d',\n",
        "]\n",
        "\n",
        "def load_features(path=FEATURES_PATH):\n",
        "    df = pd.read_csv(path)\n",
        "    df['date'] = pd.to_datetime(df['date'])\n",
        "    return df.sort_values(['sku_id', 'date']).reset_index(drop=True)\n",
        "\n",
        "def build_lagged_dataset(df):\n",
        "    df = df.copy()\n",
        "    for col in LAG_FEATURES:\n",
        "        df[f'{col}_lag1'] = df.groupby('sku_id')[col].shift(1)\n",
        "    df['day_of_week'] = df['date'].dt.dayofweek\n",
        "    return df\n",
        "\n",
        "feature_df = load_features()\n",
        "model_df = build_lagged_dataset(feature_df)\n",
        "model_cols = [f'{c}_lag1' for c in LAG_FEATURES] + ['day_of_week', 'lead_time_days', 'category', 'sku_id', 'date', 'units_sold']\n",
        "model_df = model_df[model_cols].copy()\n",
        "model_df = model_df.dropna(subset=[f'{c}_lag1' for c in LAG_FEATURES])\n",
        "\n",
        "model_df.to_csv(MODEL_DATASET_PATH, index=False)\n",
        "print(f'Saved model dataset to {MODEL_DATASET_PATH}')\n",
        "print(f'Rows after warmup drop: {len(model_df)}')\n",
        "print(model_df.head().to_string())\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 4) Train the demand forecasting model"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "HOLDOUT_DAYS = 14\n",
        "NUMERIC_FEATURES = [\n",
        "    'avg_sold_7d_lag1', 'avg_sold_14d_lag1', 'avg_sold_28d_lag1',\n",
        "    'std_sold_28d_lag1', 'cv_sold_28d_lag1', 'trend_ratio_lag1',\n",
        "    'stockout_rate_28d_lag1', 'day_of_week', 'lead_time_days',\n",
        "]\n",
        "CATEGORICAL_FEATURES = ['category']\n",
        "\n",
        "def time_based_split(df, holdout_days=HOLDOUT_DAYS):\n",
        "    cutoff_per_sku = df.groupby('sku_id')['date'].transform(\n",
        "        lambda d: d.max() - pd.Timedelta(days=holdout_days)\n",
        "    )\n",
        "    train = df[df['date'] <= cutoff_per_sku].copy()\n",
        "    test = df[df['date'] > cutoff_per_sku].copy()\n",
        "    return train, test\n",
        "\n",
        "def build_design_matrix(df, category_columns=None):\n",
        "    X = pd.get_dummies(df[CATEGORICAL_FEATURES], columns=CATEGORICAL_FEATURES)\n",
        "    X = pd.concat([df[NUMERIC_FEATURES].reset_index(drop=True), X.reset_index(drop=True)], axis=1)\n",
        "    if category_columns is not None:\n",
        "        X = X.reindex(columns=category_columns, fill_value=0)\n",
        "    return X\n",
        "\n",
        "def mean_absolute_percentage_error(y_true, y_pred):\n",
        "    y_true, y_pred = np.array(y_true), np.array(y_pred)\n",
        "    mask = y_true != 0\n",
        "    return (np.abs((y_true[mask] - y_pred[mask]) / y_true[mask])).mean() * 100\n",
        "\n",
        "model_df = pd.read_csv(MODEL_DATASET_PATH)\n",
        "model_df['date'] = pd.to_datetime(model_df['date'])\n",
        "train, test = time_based_split(model_df)\n",
        "X_train = build_design_matrix(train)\n",
        "y_train = train['units_sold']\n",
        "X_test = build_design_matrix(test, category_columns=X_train.columns)\n",
        "y_test = test['units_sold']\n",
        "\n",
        "baseline_pred = test['avg_sold_14d_lag1']\n",
        "baseline_mae = mean_absolute_error(y_test, baseline_pred)\n",
        "baseline_mape = mean_absolute_percentage_error(y_test, baseline_pred)\n",
        "\n",
        "model = RandomForestRegressor(\n",
        "    n_estimators=300, max_depth=8, min_samples_leaf=5,\n",
        "    random_state=42, n_jobs=-1,\n",
        ")\n",
        "model.fit(X_train, y_train)\n",
        "model_pred = model.predict(X_test)\n",
        "model_mae = mean_absolute_error(y_test, model_pred)\n",
        "model_mape = mean_absolute_percentage_error(y_test, model_pred)\n",
        "\n",
        "print('=== Backtest results ===')\n",
        "print(f'Naive MAE: {baseline_mae:.2f}')\n",
        "print(f'Naive MAPE: {baseline_mape:.1f}%')\n",
        "print(f'Random Forest MAE: {model_mae:.2f}')\n",
        "print(f'Random Forest MAPE: {model_mape:.1f}%')\n",
        "print(f'MAE improvement over naive baseline: {(1 - model_mae / baseline_mae) * 100:.1f}%')\n",
        "\n",
        "joblib.dump(model, MODEL_PATH)\n",
        "joblib.dump(list(X_train.columns), MODEL_COLUMNS_PATH)\n",
        "print(f'Saved model to {MODEL_PATH}')\n",
        "print(f'Saved model columns to {MODEL_COLUMNS_PATH}')\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 5) Forecast demand and generate risk flags"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "def load_features_for_prediction(path=FEATURES_PATH):\n",
        "    df = pd.read_csv(path)\n",
        "    df['date'] = pd.to_datetime(df['date'])\n",
        "    return df.sort_values(['sku_id', 'date']).reset_index(drop=True)\n",
        "\n",
        "def get_latest_snapshot(df):\n",
        "    latest = df.sort_values('date').groupby('sku_id').tail(1).copy()\n",
        "    next_date = df['date'].max() + pd.Timedelta(days=1)\n",
        "    latest['day_of_week'] = next_date.dayofweek\n",
        "    return latest, next_date\n",
        "\n",
        "def predict_established(latest_established, model, model_columns):\n",
        "    df = latest_established.copy()\n",
        "    rename_map = {\n",
        "        c: f'{c}_lag1' for c in [\n",
        "            'avg_sold_7d', 'avg_sold_14d', 'avg_sold_28d', 'std_sold_28d',\n",
        "            'cv_sold_28d', 'trend_ratio', 'stockout_rate_28d'\n",
        "        ]\n",
        "    }\n",
        "    df = df.rename(columns=rename_map)\n",
        "    numeric_cols = list(rename_map.values()) + ['day_of_week', 'lead_time_days']\n",
        "    X = pd.get_dummies(df[['category']], columns=['category'])\n",
        "    X = pd.concat([df[numeric_cols].reset_index(drop=True), X.reset_index(drop=True)], axis=1)\n",
        "    missing = set(model_columns) - set(X.columns)\n",
        "    if missing:\n",
        "        raise ValueError(f'Column mismatch: {missing}')\n",
        "    X = X.reindex(columns=model_columns, fill_value=0)\n",
        "    return model.predict(X)\n",
        "\n",
        "def predict_new_skus(latest_new, df_all):\n",
        "    established = df_all[~df_all['sku_id'].isin(NEW_SKUS)]\n",
        "    recent_28d = established.sort_values('date').groupby('sku_id').tail(28)\n",
        "    cat_avg = recent_28d.groupby('category')['units_sold'].mean()\n",
        "    return latest_new['category'].map(cat_avg).values\n",
        "\n",
        "def classify_risk(row):\n",
        "    if row['projected_demand_leadtime'] == 0:\n",
        "        return 'HEALTHY'\n",
        "    ratio = row['closing_stock'] / row['projected_demand_leadtime']\n",
        "    if ratio < 1.0:\n",
        "        return 'STOCKOUT_RISK'\n",
        "    elif ratio > 2.0:\n",
        "        return 'OVERSTOCK'\n",
        "    return 'HEALTHY'\n",
        "\n",
        "feature_df = load_features_for_prediction()\n",
        "model = joblib.load(MODEL_PATH)\n",
        "model_columns = joblib.load(MODEL_COLUMNS_PATH)\n",
        "\n",
        "latest, next_date = get_latest_snapshot(feature_df)\n",
        "print(f'Forecasting for: {next_date.date()}')\n",
        "\n",
        "is_new = latest['sku_id'].isin(NEW_SKUS)\n",
        "latest_established = latest[~is_new].copy()\n",
        "latest_new = latest[is_new].copy()\n",
        "\n",
        "latest_established['predicted_next_day_demand'] = predict_established(latest_established, model, model_columns)\n",
        "latest_established['confidence'] = 'normal'\n",
        "\n",
        "latest_new['predicted_next_day_demand'] = predict_new_skus(latest_new, feature_df)\n",
        "latest_new['confidence'] = 'low (new SKU, category-average fallback)'\n",
        "\n",
        "result = pd.concat([latest_established, latest_new], ignore_index=True)\n",
        "result['projected_demand_leadtime'] = (result['predicted_next_day_demand'] * result['lead_time_days']).round(1)\n",
        "result['risk_flag'] = result.apply(classify_risk, axis=1)\n",
        "result['cover_ratio'] = (result['closing_stock'] / result['projected_demand_leadtime']).round(2)\n",
        "\n",
        "out_cols = [\n",
        "    'sku_id', 'category', 'closing_stock', 'lead_time_days',\n",
        "    'predicted_next_day_demand', 'projected_demand_leadtime',\n",
        "    'cover_ratio', 'risk_flag', 'confidence',\n",
        "]\n",
        "result = result[out_cols].sort_values('cover_ratio')\n",
        "\n",
        "result.to_csv(RISK_PATH, index=False)\n",
        "print('Risk flags saved to', RISK_PATH)\n",
        "print(result.head(15).to_string(index=False))\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 6) Final summary and outputs"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "print(f'Cleaned data: {CLEANED_PATH.exists()} -> {CLEANED_PATH}')\n",
        "print(f'Features data: {FEATURES_PATH.exists()} -> {FEATURES_PATH}')\n",
        "print(f'Model dataset: {MODEL_DATASET_PATH.exists()} -> {MODEL_DATASET_PATH}')\n",
        "print(f'Model file: {MODEL_PATH.exists()} -> {MODEL_PATH}')\n",
        "print(f'Risk flags: {RISK_PATH.exists()} -> {RISK_PATH}')\n",
        "print('\\nRisk summary:')\n",
        "print(result['risk_flag'].value_counts().to_string())\n"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "name": "python",
      "version": "3.14"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 5
}

nb_path.write_text(json.dumps(nb, indent=1), encoding='utf-8')
print(f'Notebook created at {nb_path}')
